name: FastAPI CI/CD Pipline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-build-tag:
        runs-on: ubuntu-latest

        steps:
            # Clone Code
            - name: Checkout code
              uses: actions/checkout@v4

            # Python Config
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"

            # Dependencies
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # Run Tests
            - name: Run Tests
              run: |
                pytest

            # Build Docker
            - name: Build Docker Image
              run: |
                  docker build -t integration-app .
            
            # Git Config
            - name: Configure Git user
              run: |
                git config --local user.name "GitHub Action"
                git config --local user.email "action@github.com"

            # Create new Tag
            - name: Create and push tag
              uses: ad-m/github-push-action@v0.8.0
              if: success() # if test passed code will be tag
              with:
                  github_token: ${{ secrets.GH_PAT }}
              run: |
                  VERSION=$(date '+%Y.%m.%d-%H%M')
                  git tag -a "v$VERSION" -m "New version $VERSION"
                  git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/tarnasi/integration-code.git "v$VERSION"
