name: FastAPI CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-build-tag:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run Tests
              run: |
                pytest

            - name: Build Docker Image
              run: |
                  docker build -t integration-app .

            - name: Configure Git user
              run: |
                git config --local user.name "GitHub Action"
                git config --local user.email "action@github.com"
                git remote set-url origin https://github.com/tarnasi/integration-code.git

            - name: Create and push tag
              if: success()
              env:
                  GH_PAT: ${{ secrets.GH_PAT }}
              run: |
                  VERSION=$(date '+%Y.%m.%d-%H%M')
                  git tag -a "v$VERSION" -m "New version $VERSION"
                  git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/tarnasi/integration-code.git "v$VERSION"
